[workspace]
package.version = "0.1.0"
package.license = "GPL-3.0-or-later"
members = ["./", "bindings", "bindings/uniffi-bindgen", "moonlight-common-sys"]

[workspace.dependencies]
moonlight-common-sys = { path = "./moonlight-common-sys" }
moonlight-common = { path = "./", default-features = false }

thiserror = "2.0.18"
uniffi = "0.31.0"

openssl-sys = "0.9.109"
openssl = "0.10.73"

[workspace.lints.clippy]
too_many_arguments = "allow"
needless_range_loop = "allow"
todo = "warn"
unwrap_used = "warn"

[package]
name = "moonlight-common"
edition = "2024"
version.workspace = true
license.workspace = true

[dependencies]
bitflags = "2.9.1"
num = "0.4.3"
num-derive = "0.4.2"
num-traits = "0.2.19"

tracing = "0.1.44"

thiserror.workspace = true

uuid = { version = "1.23.4", features = ["v4", "js"] }
hex = "0.4.3"
pem = "3.0.6"
roxmltree = "0.21.1"
form_urlencoded = "1.2.2"
percent-encoding = "2.3.2"
smallvec = "1.15.1"
bytes = "1.12.0"

# Stream Proto
sans-io-time = "0.2.0"
fec-rs = { version = "0.1.0", features = ["parallel"], optional = true }
rusty_enet = { version = "0.4.0", optional = true }

# Stream c
moonlight-common-sys = { workspace = true, optional = true }

# Stream Std / Tokio
socket2 = { version = "0.6.5", optional = true }

# Stream Tokio
tokio = { version = "1.52.3", default-features = false, features = [
    "io-util",
    "net",
    "sync",
    "time",
    "macros",
], optional = true }
pin-project-lite = "0.2"

# -- Request clients
http = { version = "1.4.0", default-features = false, optional = true }
hyper = { version = "1.8.1", features = [
    "client",
    "http1",
], default-features = false, optional = true }

# ureq
ureq = { version = "3.2.0", features = [
    "rustls",
], default-features = false, optional = true }

# Hyper Client
rustls = { version = "0.23.37", default-features = false, features = ["ring", "std", "tls12"], optional = true }
hyper-util = { version = "0.1.20", features = [
    "client",
    "tracing",
], default-features = false, optional = true }
http-body-util = { version = "0.1.3", optional = true }
hyper-rustls = { version = "0.27.7", features = [
    "http1",
], default-features = false, optional = true }

# -- Crypto Backends
# OpenSSL
openssl = { workspace = true, optional = true }

# Rustcrypto
sha1 = { version = "0.10.6", default-features = false, optional = true }
sha2 = { version = "0.10.9", features = [
    "oid",
], default-features = false, optional = true }
# rsa requires this rand version for private key generation
rand_v8 = { package = "rand", version = "0.8.5", default-features = false, optional = true }
# when generating js bindings we need get random
getrandom = { version = "0.2.17", features = ["js"] }
aes = { version = "0.8.4", default-features = false, optional = true }
rsa = { version = "0.9.10", features = [
    "std",
    "sha2",
], default-features = false, optional = true }
# must be this specific version because of some other crate
der = { version = "0.7.10", default-features = false, optional = true }
spki = { version = "0.7.3", default-features = false, optional = true }
x509-cert = { version = "0.2.5", features = [
    "std",
    "pem",
    "builder",
], default-features = false, optional = true }
pkcs8 = { version = "0.10.2", default-features = false, optional = true }
signature = { version = "2.2.0", default-features = false, optional = true }
aes-gcm = { version = "0.10.3", default-features = false, features = [
    "aes",
], optional = true }
# this must match the aes version
cbc = { version = "0.1.2", default-features = false, features = [
    "block-padding",
], optional = true }

# Webrtc
sdp-types = "0.1.8"

# serde serialization for some types
serde = { version = "1.0.228", features = ["derive"], optional = true }

[features]
default = ["ureq", "std", "stream-proto", "rustcrypto"]

serde = ["dep:serde"]

# Different "runtimes"
std = ["dep:socket2"]
tokio = ["dep:tokio", "stream-proto", "dep:socket2"]

# Stream implementations
stream-proto = ["dep:fec-rs", "dep:rusty_enet"]
stream-c = ["dep:moonlight-common-sys"]

# Crypto implementations
openssl = ["dep:openssl"]
rustcrypto = [
    "dep:sha1",
    "dep:sha2",
    "dep:rand_v8",
    "dep:aes",
    "dep:rsa",
    "dep:der",
    "dep:spki",
    "dep:x509-cert",
    "dep:signature",
    "dep:pkcs8",
    "dep:aes-gcm",
    "dep:cbc",
]

# Request implementations
ureq = ["dep:http", "dep:hyper", "dep:ureq", "dep:rustls"]
tokio-hyper = [
    "dep:http",
    "dep:rustls",
    "dep:hyper",
    "dep:hyper-util",
    "dep:http-body-util",
    "dep:hyper-rustls",
    "tokio",
]

# Logs sensitive information: e.g. private keys and sensitive values used in encryption / decryption
__tracing_sensitive = []

[lints]
workspace = true

[dev-dependencies]
tokio = { version = "1.49.0", features = ["full"] }

# CLI args for examples
clap = { version = "4.6.1", features = ["derive"] }

# GStreamer for video and audio playout
gstreamer = { version = "0.25.1" }
gstreamer-app = { version = "0.25.0" }

# For testing: very nice logging
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
venator = { version = "1.1.0" }

# openssl version above this version don't compile in cross-rs (x86_64-pc-windows-gnu)
# See https://github.com/openssl/openssl/issues/29818
openssl-src = "=300.5.3"
openssl-sys = "=0.9.109"

[package.metadata.cargo-shear]
ignored = [
    "getrandom",   # getrandom must be ignored, because rand depends on it, but without the js feature
    "openssl-src",
    "openssl-sys",
]

[[example]]
name = "client-simple"
path = "examples/client-simple.rs"
required-features = ["ureq", "std", "rustcrypto"]

[[example]]
name = "client-stream"
path = "examples/client-stream.rs"
required-features = ["ureq", "std", "rustcrypto"]

[[example]]
name = "client-common-c"
path = "examples/client-common-c.rs"
required-features = ["ureq", "std", "openssl", "stream-c"]

[[example]]
name = "client-tokio"
path = "examples/client-tokio.rs"
required-features = ["tokio-hyper", "tokio", "rustcrypto"]

[lib]
doctest = false
